server:
  port: 8083
spring:
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.travelsmart.notification_service.config.CustomSerializer
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.travelsmart.notification_service.config.CustomDeserializer
      properties:
        spring.json.trusted.packages: "*"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/media_travel_db}
    password: ${DBMS_PASSWORD:1234}
    username: ${DBMS_USERNAME:root}
  cloud:
    compatibility-verifier:
      enabled: false
  application:
    name: notification-service
  kubernetes:
    discovery:
      enabled: true  # Enable Kubernetes-based service discovery
      all-namespaces: true  # Optional: Discover services only in the same namespace

management:
  tracing:
    sampling:
      probability:1.0
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    tags:
      application: ${spring.application.name}

eventuatelocal:
  kafka:
    bootstrap:
      servers: localhost:9094
eventuate:
  database:
    schema: eventuate



api:
  prefix: /notification
notification:
  email:
    brevo-url: https://api.brevo.com
    brevo-apiKey: ${BREVO-API-KEY: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}
## Additional configuration if needed
#logging:
#  level:
#    io.eventuate.tram: DEBUG
#    org.apache.kafka: DEBUG