apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: identity-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
