server:
  port: 8082
  servlet:
    context-path: /blog
spring:
  application:
    name: blog-service
  kubernetes:
    discovery:
      enabled: true  # Enable Kubernetes-based service discovery
      all-namespaces: true  # Optional: Discover services only in the same namespace
  security:
    metrics:
      enabled: false  # Tắt metrics bảo mật của Spring Security
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/blog_travel_db}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    password: ${DBMS_PASSWORD:1234}
    username: ${DBMS_USERNAME:root}
  jpa:
    hibernate:
      ddl-auto: none
      enable_lazy_load_no_trans: true
  cloud:
    compatibility-verifier:
      enabled: false
  liquibase:
    enabled: true
api:
  prefix: /blog
management:
  tracing:
    sampling:
      probability: 0.1
  metrics:
    enable:
      hikari: false
    export:
      prometheus:
        enabled: true
        use-exemplars: false  # Tắt exemplars cho Prometheus metrics
  endpoints:
    web:
      exposure:
        include: "prometheus,health"   # Bật các endpoint `metrics` và `health`
  endpoint:
    metrics:
      enabled: true                 # Kích hoạt endpoint `metrics`
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
feign:
  url:
    media: ${MEDIA-SERVICE-URL:http://localhost:8088}
    profile: ${PROFILE-SERVICE-URL:http://localhost:8081}
swagger: "2.0"
openapi: "3.0.0"
app:
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8888
