server:
  port: 8085
  servlet:
    context-path: /trip
api:
  prefix: /trip
spring:
  application:
    name: trip-service
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trip_travel_db
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
      enable_lazy_load_no_trans: true
  liquibase:
    enabled: true
geoapify:
  key: d1e2afb1ba924f9ebbbb3bd407e72b63
  url: https://api.geoapify.com/
  search: /v1/geocode/search
  reverse: /v1/geocode/reverse
  placeDetail: /v2/place-details
  routing: /v1/routing
management:
  endpoints:
    web:
      exposure:
        include: "prometheus"   # Bật các endpoint `metrics` và `health`
  endpoint:
    metrics:
      enabled: true                 # Kích hoạt endpoint `metrics`
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
swagger: "2.0"
openapi: "3.0.0"
app:
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8888

