CREATE DATABASE IF NOT EXISTS  identity_travel_db;
CREATE DATABASE IF NOT EXISTS  trip_travel_db;
CREATE DATABASE IF NOT EXISTS  profile_travel_db;
CREATE DATABASE IF NOT EXISTS  media_travel_db;
CREATE DATABASE IF NOT EXISTS  location_travel_db;