server:
  port: 8081
spring:
  application:
    name: profile-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/profile_travel_db
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
      enable_lazy_load_no_trans: true
  cloud:
    compatibility-verifier:
      enabled: false
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  liquibase:
    enabled: true
management:
  tracing:
    sampling:
      probability:1.0
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    tags:
      application: ${spring.application.name}
  


#eventuatelocal:
#  kafka:
#    bootstrap:
#      servers: localhost:9094
#  zookeeper:
#    connection:
#      string: localhost:2181
#
#eventuate:
#  database:
#    schema: eventuate

cloud:
  cloudName: dzumda5fa
  apiKey: 959631823469922
  apiSecret: NFULtoFFUlC6qCPN1BSiRw5KUGk
  secure: true
api:
  prefix: /profile
token:
  tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
  accessExpiration: 1500000
  refreshExpiration: 604800000
## Additional configuration if needed
#logging:
#  level:
#    io.eventuate.tram: DEBUG
#    org.apache.kafka: DEBUG
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
swagger: "2.0"
openapi: "3.0.0"
app:
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8888