server:
  port: 8081
  servlet:
    context-path: /profile
spring:
  application:
    name: profile-service
  kubernetes:
    discovery:
      enabled: true  # Enable Kubernetes-based service discovery
      all-namespaces: true  # Optional: Discover services only in the same namespace
  sleuth:
    enabled: true
    sampler:
      probability: 1.0  # Adjust trace sample rate if needed
    web:
      client:
        enabled: true  # If you want to trace web client calls
    exporter:
      zipkin:
        enabled: true
        baseUrl: http://172.30.0.4:9411/api/v2/spans  # Change this to your Zipkin server URL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/profile_travel_db}
    password: ${DBMS_PASSWORD:1234}
    username: ${DBMS_USERNAME:root}
  jpa:
    hibernate:
      ddl-auto: update
      enable_lazy_load_no_trans: true
  cloud:
    compatibility-verifier:
      enabled: false
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.travelsmart.profile_service.config.CustomSerializer
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.travelsmart.profile_service.config.CustomDeserializer
      properties:
        spring.json.trusted.packages: "*"
  liquibase:
    enabled: true
management:
  tracing:
    sampling:
      probability: 1.0
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: "prometheus"   # Bật các endpoint `metrics` và `health`
  endpoint:
    metrics:
      enabled: true                 # Kích hoạt endpoint `metrics`



#eventuatelocal:
#  kafka:
#    bootstrap:
#      servers: localhost:9094
#  zookeeper:
#    connection:
#      string: localhost:2181
#
#eventuate:
#  database:
#    schema: eventuate

cloud:
  cloudName: dzumda5fa
  apiKey: 959631823469922
  apiSecret: NFULtoFFUlC6qCPN1BSiRw5KUGk
  secure: true
api:
  prefix: /profile
token:
  tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
  accessExpiration: 1500000
  refreshExpiration: 604800000
## Additional configuration if needed
#logging:
#  level:
#    io.eventuate.tram: DEBUG
#    org.apache.kafka: DEBUG
feign:
  url:
    media: ${MEDIA-SERVICE-URL:http://localhost:8088}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
swagger: "2.0"
openapi: "3.0.0"
app:
  cors:
    allowedOrigins: http://localhost:8888

