server:
  port: 8086
  servlet:
    context-path: /review
api:
  prefix: /review
spring:
  application:
    name: review-service
  sleuth:
    enabled: true
    sampler:
      probability: 1.0  # Adjust trace sample rate if needed
    web:
      client:
        enabled: true  # If you want to trace web client calls
    exporter:
      zipkin:
        enabled: true
        baseUrl: http://172.30.0.4:9411/api/v2/spans  # Change this to your Zipkin server URL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/review_travel_db
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
      enable_lazy_load_no_trans: true
  cloud:
    compatibility-verifier:
      enabled: false
  liquibase:
    enabled: true
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
management:
  tracing:

    sampling:
      probability: 0.1
#  micrometer:
#    tracing:
#      reporting:
#        zipkin:
#          enabled: true
#          endpoint: http://localhost:9411/api/v2/spans  # Replace with your Zipkin server URL
  endpoints:
    web:
      exposure:
        include: "prometheus"   # Bật các endpoint `metrics` và `health`
  endpoint:
    metrics:
      enabled: true                 # Kích hoạt endpoint `metrics`
swagger: "2.0"
openapi: "3.0.0"
app:
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8888
