server:
  port: 8084
  servlet:
    context-path: /location
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: location-service
  kubernetes:
    discovery:
      enabled: true  # Enable Kubernetes-based service discovery
      all-namespaces: true  # Optional: Discover services only in the same namespace
  sleuth:
    enabled: true
    sampler:
      probability: 1.0  # Adjust trace sample rate if needed
    web:
      client:
        enabled: true  # If you want to trace web client calls
    exporter:
      zipkin:
        enabled: true
        baseUrl: http://172.30.0.4:9411/api/v2/spans  # Change this to your Zipkin server URL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/location_travel_db}
    password: ${DBMS_PASSWORD:1234}
    username: ${DBMS_USERNAME:root}
  jpa:
    hibernate:
      ddl-auto: update
      enable_lazy_load_no_trans: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.spatial.dialect.mysql.MySQLSpatialDialect
  liquibase:
    enabled: false

  cloud:
    compatibility-verifier:
      enabled: false
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.travelsmart.location_service.config.CustomSerializer
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.travelsmart.location_service.config.CustomDeserializer
      properties:
        spring.json.trusted.packages: "*"
api:
  prefix: /location
#geoapify:
#  key: d1e2afb1ba924f9ebbbb3bd407e72b63
#  url: https://api.geoapify.com/
#  search: /v1/geocode/search
#  reverse: /v1/geocode/reverse
#  placeDetail: /v2/place-details
nominatim:
  url: https://nominatim.openstreetmap.org
  version: jsonv2
  search: /search
  reverse: /reverse
  lookup: /lookup
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
swagger: "2.0"
openapi: "3.0.0"
app:
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8888
feign:
  url:
    media: ${MEDIA-SERVICE-URL:http://localhost:8088}
    review: ${REVIEW-SERVICE-URL:http://localhost:8086}
management:
  tracing:
    sampling:
      probability: 0.1
  endpoints:
    web:
      exposure:
        include: "prometheus"   # Bật các endpoint `metrics` và `health`
  endpoint:
    metrics:
      enabled: true

#  micrometer:
#    tracing:
#      reporting:
#        zipkin:
#          enabled: true
#          endpoint: http://localhost:9411/api/v2/spans  # Replace with your Zipkin server URL

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


